version: '3.9'

services:
  mariadb:
    image: mariadb:11.1
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: weatherData
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--innodb_initialized", "--connect"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - backend-service
    volumes:
      - ./backend/docker/db:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    ports:
      - 8080:8080
    restart: always
    environment:
      MARIADB_HOST: mariadb
      MARIADB_PORT: 3306
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: weatherData
      PORT: 8080
    networks:
      - backend-service
    depends_on:
      mariadb:
        condition: service_healthy

  dashboard:
    build: ./dashboard
    ports:
      - 4200:4200
    restart: always
    depends_on:
      - backend

networks:
  backend-service:
    driver: bridge